version: "3"

volumes:
  magento2-webroot:
    external: true

services:
  php:
    volumes:
      - magento2-webroot:/var/www/html
  cli:
    volumes:
      - magento2-webroot:/var/www/html
  nginx:
    volumes:
      - magento2-webroot:/var/www/html
